### ISSUE TITLE
AZURE AKS: Container name must be no more than 63 characters.

### ISSUE THREAD

**Issue by hetii** [asteven/local-zfs-provisioner#1]
Hi, I try to use this project under azure aks but after creating pvc+pod I get this error:

`Warning    ProvisioningFailed    84s (x5 over 5m9s)     asteven/local-zfs_aks-nodepool1-28147575-1_37a4a58d-a7f9-11e9-a72a-000d3a23af49  failed to provision volume with StorageClass "local-zfs": Failed to create volume pvc-65caa7ab-a7fc-11e9-9b45-62756ec816a8 at aks-nodepool1-28147575-1:/var/lib/local-zfs-provisioner/pvc-65caa7ab-a7fc-11e9-9b45-62756ec816a8: Pod "aks-nodepool1-28147575-1-pvc-65caa7ab-a7fc-11e9-9b45-62756ec816a8-create" is invalid: spec.containers[0].name: Invalid value: "aks-nodepool1-28147575-1-pvc-65caa7ab-a7fc-11e9-9b45-62756ec816a8-create": must be no more than 63 characters`

**Comment by asteven** [comment]
Hi there,

Thanks for reporting the issue.
Seems I was lucky until now to end on nodes with short hostnames.
I've changed the way the pod names are generated so they are now always <=50 chars.
